### ISSUE TITLE
Please list your build test environment/platforms

### ISSUE THREAD

**Issue by aenertia** [allencch/med#1]
Hi there;

I just built with Ubutn 16.04 with kubuntu backport packages for the needed qt5tools dependencies. But I just get segfaulting resulantant binaries. Some errata text as to what Distro, and package versions were used to test/build would be helpful. I can always docker container build if needed but I need some more info on the test environment first.

**Comment by allencch** [comment]
@aenertia , I would like to know which binary file you are running?
I am using Arch Linux with Qt 5.8 and jsoncpp 1.8.0.
CMake should detect the required libraries.
May be you can run `ldd` to check which library is missing.

**Comment by allencch** [comment]
@aenertia , I guess the issue was cannot locate process.ui and main-qt.ui. Because during my development, I execute the binary file with the same directory that contains process.ui and main-qt.ui.

**Comment by aenertia** [comment]
I did a clean install of the ancient and upgraded box to ubuntu 17.04
yesterday; looking at the ldd of the file compiled on that one. On the new
install

linux-vdso.so.1 =>  (0x00007ffefed88000)
libmed.so => not found
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007fb37036f000)
libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(0x00007fb36fb14000)
libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
(0x00007fb36f3de000)
libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
(0x00007fb36ed13000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(0x00007fb36e988000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb36e771000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb36e3aa000)
/lib64/ld-linux-x86-64.so.2 (0x000055b7d4ac4000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb36e0a1000)
libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
(0x00007fb36de0d000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb36dbf1000)
libGL.so.1 => /usr/lib/nvidia-378/libGL.so.1 (0x00007fb36d95f000)
libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16
(0x00007fb36d72d000)
libicui18n.so.57 => /usr/lib/x86_64-linux-gnu/libicui18n.so.57
(0x00007fb36d2b3000)
libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57
(0x00007fb36cf0b000)
libpcre16.so.3 => /usr/lib/x86_64-linux-gnu/libpcre16.so.3
(0x00007fb36cca2000)
libdouble-conversion.so.1 =>
/usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007fb36ca91000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb36c88b000)
libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0
(0x00007fb36c577000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb36c36f000)
libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6
(0x00007fb36c0c2000)
libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3
(0x00007fb36be9c000)
libGLX.so.0 => /usr/lib/nvidia-378/libGLX.so.0 (0x00007fb36bc6c000)
libGLdispatch.so.0 => /usr/lib/nvidia-378/libGLdispatch.so.0
(0x00007fb36b981000)
libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57
(0x00007fb369f04000)
libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fb369c91000)
libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb369958000)
libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fb369746000)
libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb369522000)
libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb36931e000)
libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
(0x00007fb369118000)


Looks like it is missing the libmed.so as well since it's never added to LD
library path - you should add make install defines

**Comment by aenertia** [comment]
This wasn't the error I got the other day tho. It was segfault due to
something to do with window template ui in qt - i.e looked like issue with
versions

**Comment by allencch** [comment]
@aenertia , I have improved the CMakeLists.txt that install the all required files. Furthermore, there is a Arch Linux package build script too.
Please check whether that helps.
