### ISSUE TITLE
Scanner can't find an existing value

### ISSUE THREAD

**Issue by Anarky** [allencch/med#3]
Hello,

I'm trying to find an address on PCSX2 to disable interlacing on a game, [as seen in this topic](https://forums.pcsx2.net/Thread-No-interlacing-codes).
I tried to practice with Dead or Alive 2 Hardcore like in the topic; in the memory editor I can go to 0x203962FC and find `08 00 42 64`, or `1682046984`. But when I try to find this value in the main window it doesn't find this address, as you can see in this screenshot:

![2018-12-31-003003_1920x1080_scrot](https://user-images.githubusercontent.com/6974775/50552450-cec12100-0c93-11e9-831a-7f1099631905.png)

**Comment by allencch** [comment]
Hi @Anarky , thanks for notifying. I have to look into the memory scanning algorithm again.

**Comment by Anarky** [comment]
Thanks for your quick answer!
Not sure if it helps but scanmem/GameConqueror couldn't find the address either, even when I specified a byte array. I was beginning to think Linux's memory management was too different to find PCSX2 cheats.

**Comment by allencch** [comment]
> Not sure if it helps but scanmem/GameConqueror couldn't find the address either, even when I specified a byte array.

Thanks, this is a great info. Because I used the same conditions as scanmem on the target  `maps`.

https://github.com/allencch/med/blob/b5ab5826649ccde176831f94d256a3d359d803dd/src/med/MedCommon.cpp#L155-L169

Possibly the target address is not in the block.
