### ISSUE TITLE
issue with linux assembly

### ISSUE THREAD

**Issue by jay-76** [allencch/med#5]
its not a bug, its mainly stupidity
i dont know if you have a version to download,for linux. or only git stuff, which i have basically no clue about. i did some stuff got a master,installed cmake, it says something is missing.. mint doesnt offer a clue what exactly.
i would be happy about a sh or any sort of linux startable version , where i would not need to learn more then 4 hours how to just get a useful file together. 
i mean, 4 hours,and a couple folder later,i still have nothing to show,or run for.

thanks,and sorry i have to use that way,no other basic contactmethod.

**Comment by allencch** [comment]
Hi @jay-76 , you are using Linux Mint?
You can try this. https://github.com/OmniNegro123/med/commit/9100db7ad44e0b1e36e06d942d84325d2bd95aed

Hopefully it helps.

**Comment by jay-76** [comment]
yes mint mate, thanks that one helped,even if "2.5 cd build" was missing, basically i missed the first line with all those apps to install. 
thanks again
it works flawless and yes its much better then the basic gc. 
thanks for your time, making it.aswell as pointing that install list out.
regards Jay
