### ISSUE TITLE
Needs GNU Readline

### ISSUE THREAD

**Issue by gavinunderdown** [allencch/med#6]
The build instructions in the readme do not say that it requires the GNU readline library, however, on a relatively fresh install of Debian Bullseye, I was unable to build the ui without first `sudo apt install -y libreadline-dev`

Readline headers need to be installed to build.

**Comment by allencch** [comment]
Thanks for the info. Updated readme 6c03e59badc3f08df72a8bbea8f4ea553873f4ff
