### ISSUE TITLE
Crash durring compile

### ISSUE THREAD

**Issue by aknight2015** [allencch/med#8]
This is the error I get. No idea why.
[ 36%] Building CXX object CMakeFiles/med-cli.dir/src/cli/main.cpp.o
/home/aknight2015/Programs/med-3.8.1/src/cli/main.cpp:5:10: fatal error: readline/readline.h: No such file or directory
    5 | #include <readline/readline.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/med-cli.dir/build.make:90: CMakeFiles/med-cli.dir/src/cli/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:243: CMakeFiles/med-cli.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by allencch** [comment]
Looks like you don't have `readline` installed. If Ubuntu-based, can install `libreadline-dev`.

**Comment by aknight2015** [comment]
THanks for the help. That solved it.
