### ISSUE TITLE
make failed - all listed requirements installed

### ISSUE THREAD

**Issue by Jfullernz** [allencch/med#9]
OS Ubuntu 23.04
Linux jasmine-PC 6.2.0-23-generic #23-Ubuntu SMP PREEMPT_DYNAMIC Wed May 17 16:55:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Following your install guide, first without cxxtest and also with it installed, I get the following output.  I can't see a readline.h in your files/folders either.

 80%] Automatic MOC for target testfile
[ 80%] Built target testfile_autogen
[ 80%] Built target testfile
[ 80%] Automatic MOC for target mem_ed
[ 80%] Built target mem_ed_autogen
[ 80%] Built target mem_ed
[ 80%] Automatic MOC for target med-ui
[ 80%] Built target med-ui_autogen
[ 80%] Built target med-ui
[ 80%] Automatic MOC for target med-cli
[ 80%] Built target med-cli_autogen
[ 80%] Building CXX object CMakeFiles/med-cli.dir/src/cli/main.cpp.o
/home/jasmine/editors/med/src/cli/main.cpp:5:10: fatal error: readline/readline.h: No such file or directory
    5 | #include <readline/readline.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/med-cli.dir/build.make:90: CMakeFiles/med-cli.dir/src/cli/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:243: CMakeFiles/med-cli.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by allencch** [comment]
This should solve the issue https://github.com/allencch/med/issues/8#issuecomment-1486400568 , and it is written in [README.md](https://github.com/allencch/med#build-instruction)
